name: React App CI
on: [ workflow_dispatch,push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd server
          npm install --force
          cd ../client
          npm install

      - name: Start backend server
        run: cd server && npm start &

      - name: Wait for backend to start
        run: sleep 10

      - name: Run frontend tests
        run: cd client && npm run vitest:run

      - name: Stop backend server
        run: kill $(lsof -t -i:4000)

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install client
        run: npm ci
        working-directory: ./client
      - name: Lint client code
        run: npm run lint:warns
        working-directory: ./client
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: ./client
      - name: Build application
        run: npm run build
        working-directory: ./client

